apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "jwt-validation"
  namespace: <namespace>
spec:
  jwtRules:
  - fromHeaders:
    - name: <header-name>
#    replace with your issuer
    issuer: <issuer_uri>
    jwksUri: <jwk_wellknow_uri>
    forwardOriginalToken: true
